# Generated by Django 5.0.6 on 2024-07-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='receitas',
            old_name='categorys',
            new_name='category',
        ),
    ]
