# Generated by Django 5.0.6 on 2024-06-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.category'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='receitas/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
