# Generated by Django 5.0.6 on 2024-07-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_categorys_category_and_more'),
    ]

    operations = [
    ]
