# Generated by Django 5.0.6 on 2024-06-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_rename_category_categorys_alter_receitas_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='receitas',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.category'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
